container_comm_host = "0.0.0.0"
container_comm_port = 50051
runtime_path = "../rena-runtime"

[inference_engine]
type = "openai"
model = "gpt-5-mini"
max_tokens = 20480
temperature = 0
url = "https://api.openai.com"


[discovery]
type = "static"

[[discovery.apps]]
name = "hello_world"
path = "file://../examples/mcp-servers/hello-world"
agent_protocol = "mcp"
runtime = "python"
command = "python"
args = ["-m", "mcp_server_hello_world"]
scripts = ["pip install ."]
